### ISSUE TITLE
exception after startup

### ISSUE THREAD

**Issue by meejah** [gridsync/gridsync#23] opened 2016-01-23 16:22 UTC
gridsync looks really nice!

I tried it out, and after getting through the nice setup prompts (and after re-starting) I get the following exception:

```
Traceback (most recent call last):
  File "/home/mike/src/gridsync/venv/bin/gridsync", line 9, in <module>
    load_entry_point('gridsync==0.0.1', 'console_scripts', 'gridsync')()
  File "/home/mike/src/gridsync/gridsync/cli.py", line 64, in main
    gridsync.start()
  File "/home/mike/src/gridsync/gridsync/server.py", line 174, in start
    self.initialize_gateways()
  File "/home/mike/src/gridsync/gridsync/server.py", line 59, in initialize_gateways
    for local_dir, dircap in contents.items():
AttributeError: 'str' object has no attribute 'items'
```

I installed on Debian jessie in a virtualenv created with ``--system-site-packages`` to pick up python-pyqt5 packages, and then ``pip install -e .`` to install gridsync.

**Comment by crwood** [comment] 2016-01-23 18:55
Hi meejah! I wasn't expecting anyone to try using this just yet (though I'm glad to see some interest already)!

The startup sequence (among other things) is indeed broken in a few ways right now: basically, the current setup 'wizard' is just a placeholder for the new/improved one that I haven't yet had the chance to implement. I'll be working on it this week, however, and will update this issue once it's in place and working. Stay tuned!

**Comment by crwood** [comment] 2016-02-25 20:53
This specific issue was caused by incompatibilities between the old and new configuration file formats but should be fixed (albeit still somewhat hackishly) as of https://github.com/gridsync/gridsync/commit/ac1e0055b7d310dcc99390dc0b43239864a5605f. If you have an older configuration file (at `~/.config/gridsync/config.yml`) you may need to remove it.

**Closed by crwood** 2016-02-25 20:53 UTC
